# Generated by Django 2.1.15 on 2022-09-11 02:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('cedula', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('monto', models.CharField(max_length=50)),
                ('pagado', models.CharField(max_length=50)),
            ],
        ),
    ]
